#pragma once

DECLARE_LOG_CATEGORY_EXTERN(LogHWGA, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAIUtility, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI_NpcStates, Log, All);
