#pragma once

DECLARE_LOG_CATEGORY_EXTERN(LogHWGA, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAIUtility, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI_NpcStates, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAIUtility_ChaseLaser, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI_NavLink, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogCharacter_FV, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI_Focus, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogAI_Perception, Log, All);
